### PR TITLE
GB - added content GET API

### PR DESCRIPTION
**Pull request by sgurjeet**
Added constants, utils, response handler, validation helpers
removed example code

### CODE REVIEW

**Review by haloboy777 — APPROVED** [review]
Looks good from my side.

**Review by khanna98 — CHANGES_REQUESTED** [review]
Please check - [Joi](https://joi.dev/api/?v=17.4.0), and try to implement it.

**Comment by haloboy777** [comment]
> Please check - [Joi](https://joi.dev/api/?v=17.4.0), and try to implement it.

We're skipping this for now. I think this merge should be approved now.

**Review by khanna98 — APPROVED** [review]
Since we are not continuing with Joi as of now. Approving the PR

**Pull request merged**
